from tools.notification_tool import send_email_notification
import json
from datetime import datetime, timedelta

def run_admin_agent(state: dict) -> dict:
    """
    Admin Agent: Task reminders, appointment tracking, family updates, weekly summaries.
    """
    print("[Admin Agent] Running daily task check...")

    today = datetime.now()
    actions_taken = []

    # Check upcoming appointments
    for appt in state.get("appointments", []):
        if appt.get("scheduled_date") and not appt.get("confirmed"):
            appt_date = datetime.fromisoformat(appt["scheduled_date"])
            days_until = (appt_date - today).days

            if days_until == 2:
                # 48-hour reminder
                message = (f"Reminder: You have an appointment with "
                           f"{appt['provider']} ({appt['specialty']}) in 2 days "
                           f"on {appt['scheduled_date']}.")
                if state.get("caregiver_email"):
                    send_email_notification(
                        to_email=state["caregiver_email"],
                        subject="Appointment Reminder — 48 Hours",
                        body=message
                    )
                actions_taken.append("48hr_appointment_reminder_sent")

    # Weekly summary (every 7 days)
    if state.get("recovery_day", 0) % 7 == 0 and state.get("recovery_day", 0) > 0:
        summary = generate_weekly_summary(state)
        if state.get("caregiver_email"):
            send_email_notification(
                to_email=state["caregiver_email"],
                subject=f"Weekly Recovery Summary — Week {state['recovery_day'] // 7}",
                body=summary
            )
        actions_taken.append("weekly_summary_sent")

    state["last_admin_run"] = datetime.now().isoformat()
    state["admin_actions_today"] = actions_taken
    state["current_agent"] = "complete"

    print(f"[Admin Agent] Done. Actions: {actions_taken}")
    return state

def generate_weekly_summary(state: dict) -> str:
    history = state.get("check_in_history", [])
    week_num = state.get("recovery_day", 7) // 7
    recent = history[-7:]

    green = sum(1 for c in recent if c.get("classification") == "GREEN")
    yellow = sum(1 for c in recent if c.get("classification") == "YELLOW")
    red = sum(1 for c in recent if c.get("classification") == "RED")

    return f"""Weekly Recovery Summary — Week {week_num}
Patient: {state.get('patient_name')}
Diagnosis: {state.get('diagnosis')}

Check-in summary (last 7 days):
✅ Green days: {green}
⚠️  Yellow days: {yellow}
🔴 Red days: {red}

{'All medications on track.' if yellow == 0 and red == 0 else 'Some medication or symptom concerns noted — see daily logs.'}

Next appointment: {state['appointments'][0]['provider'] if state.get('appointments') else 'None scheduled'}

This summary was generated by Nexus — your post-discharge recovery co-pilot."""